= Setting up Smackage
:source-highlighter: pygments

Setting up Smackage is relatively straightforward. Launch a terminal emulator and follow along.

== Compiling Smackage

First, we'll clone the Smackage repository into a temporary directory.

[source, bash]
----
cd /tmp
git clone git://github.com/standardml/smackage.git 
----

Now we'll compile Smackage using MLton.

[source, bash]
----
cd smackage
make mlton
----

This creates an executable in the +bin+ subdirectory.

== Setting up SML/NJ and MLton

Next, we'll add the directory where Smackage will put its packages to our compilers' path maps.

=== SML/NJ

Setting up the path map for SML/NJ is a trivial one-liner:

[source, bash]
----
echo "SMACKAGE $HOME/.smackage/lib" > ~/.smlnj-pathconfig
----

This creates a a hidden file called +.smlnj-pathconfig+ under your home directory and sends the output of +echo+ to it. Bash expands +$HOME+ to the path to your home directory before redirecting the output to the file.

=== MLton

MLton doesn't have user-specific path maps, so we'll edit the system-wide path map file. Since it's located in a write-protected folder, we'll need to use +sudo+:

[source, bash]
----
sudo nano /usr/lib/mlton/mlb-path-map
----

Enter your password when prompted. The file should now open in the _nano_ text editor. Assuming your user is called *aio*, add the following line at the end of the file:

....
SMACKAGE /home/aio/.smackage/lib
....

Now save the file by typing +CTRL-O+ and close _nano_ by typing +CTRL-X+.
